sh execute.sh >> saida.txt
sh execute.sh >> saida.txt
sh execute.sh >> saida.txt
sh execute.sh >> saida.txt
sh execute.sh >> saida.txt
sh execute.sh >> saida.txt
sh execute.sh >> saida.txt
sh execute.sh >> saida.txt
sh execute.sh >> saida.txt
sh execute.sh >> saida.txt
grep "F1: " saida.txt